services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - agri-data:/data/db

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  agri-data: